### ISSUE TITLE
ClassCastException in AsymmetricGridView

### ISSUE THREAD

**Issue by bhuvneshvarma** [felipecsl/AsymmetricGridView#40]
I am trying to use [AsymmetricGridView][1] to implement facebook like grid.Seeing the github usage guide i did as shown in below code.But its crashing at AsymmetricGridViewAdapter giving run time exception caused by class cast exception.I need to make my custom object to get and set data.How can i do it with AsymmetricItem?

  Exception-

    java.lang.RuntimeException: An error occured while executing doInBackground()
                at com.felipecsl.asymmetricgridview.library.AsyncTaskCompat$3.done(AsyncTaskCompat.java:265)
                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                at com.felipecsl.asymmetricgridview.library.AsyncTaskCompat$SerialExecutor$1.run(AsyncTaskCompat.java:192)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)
         Caused by: java.lang.ClassCastException: DummyObjecct cannot be cast to com.felipecsl.asymmetricgridview.library.model.AsymmetricItem
                at com.felipecsl.asymmetricgridview.library.widget.AsymmetricGridViewAdapter$ProcessRowsTask.doInBackground(AsymmetricGridViewAdapter.java:308)
                at com.felipecsl.asymmetricgridview.library.widget.AsymmetricGridViewAdapter$ProcessRowsTask.doInBackground(AsymmetricGridViewAdapter.java:300)
                at com.felipecsl.asymmetricgridview.library.AsyncTaskCompat$2.call(AsyncTaskCompat.java:253)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at com.felipecsl.asymmetricgridview.library.AsyncTaskCompat$SerialExecutor$1.run(AsyncTaskCompat.java:192)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)

Code

    mDummmyList=new ArrayList<DummyObjecct>();
    mObject=new DummyObjecct();
    for(int i=0;i<50;i++) {
    mObject.setA(a);
    mDummmyList.add(mObject);
    }
    mGridView=(AsymmetricGridView)rootView.findViewById(R.id.asymmetricgridView);
    mGridView.setRequestedColumnWidth(Utils.dpToPx(mHomeActivity.getApplicationContext(),    120));
        mListAdapter = new PhotosListAdapter(getActivity().getApplicationContext(),mDummmyList);
        AsymmetricGridViewAdapter asymmetricAdapter =new AsymmetricGridViewAdapter<>(getActivity().getApplicationContext(),    mGridView, mListAdapter);
        mGridView.setAdapter(asymmetricAdapter);

DummyObject.java

    public class DummyObjecct {
        public int getA() {
            return a;
        }
    
        public void setA(int a) {
            this.a = a;
        }
    
        private int a;
    }
PhotosListAdapter

    public class PhotosListAdapter extends BaseAdapter{
        ArrayList<DummyObjecct> mPhotos;
        Context mContext;
        public PhotosListAdapter(Context context,ArrayList<DummyObjecct> albumList)
        {
            mContext=context;
            mPhotos=albumList;
        }
        @Override
        public int getCount() {
            return mPhotos.size();
        }
    
        @Override
        public Object getItem(int i) {
            return mPhotos.get(i);
        }
    
        @Override
        public long getItemId(int i) {
            return i;
        }
    
        @Override
        public View getView(int i, View view, ViewGroup viewGroup) {
    
            if (view == null) {
                LayoutInflater layoutInflater = LayoutInflater.from(mContext);
                view = layoutInflater.inflate(R.layout.gallery_item, null);
            }
            ImageView mImage = (ImageView) view.findViewById(R.id.galleryimage);
            mImage.setImageResource(mPhotos.get(i).getA());
            return view;
        }
    }

  [1]: https://github.com/felipecsl/AsymmetricGridView

**Comment by felipecsl** [comment]
Your `DummyObject` class needs to implement the `AsymmetricItem` interface:
