### ISSUE TITLE
Hi , getting following exception  Invalid item position 66(offset:66).state:8007-11 17:14:19.569 29522-

### ISSUE THREAD

**Issue by saikiran1220** [felipecsl/AsymmetricGridView#58]
29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime: FATAL EXCEPTION: main
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime: Process: com.felipecsl.asymmetricgridview.app, PID: 29522
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 66(offset:66).state:80
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:603)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:746)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5443)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
07-11 17:14:19.569 29522-29522/com.felipecsl.asymmetricgridview.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by saikiran1220** [comment]
Ho to add new items , while i am trying to add new items when last element is reached getting following above exception

**Comment by felipecsl** [comment]
I haven't really finished the RecyclerView implementation yet, so there's still a lot of rough edges for now.
